[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "dmcp"
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.10.4",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.2",
]
