name: Test with uv and pytest

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.7.20"

      - name: run tests
        run: uv run --dev pytest
